// <auto-generated />
using System;
using FreestyleApplication.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace FreestyleApplication.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20210609115101_Competition added")]
    partial class Competitionadded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.7")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FreestyleApplication.Models.Competition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Competition");
                });

            modelBuilder.Entity("FreestyleApplication.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("CompetitionId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nickname")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CompetitionId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Atleta a 11 anos",
                            Email = "rafael.ffs@hotmail.com",
                            Name = "Rafael",
                            Nickname = "Fashola",
                            Password = "teste123"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Atleta a 10 anos",
                            Email = "gabriel@hotmail.com",
                            Name = "Gabriel",
                            Nickname = "Bibi",
                            Password = "teste123"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Atleta a 09 anos",
                            Email = "iago@hotmail.com",
                            Name = "Iago",
                            Nickname = "Pedalantis",
                            Password = "teste123"
                        });
                });

            modelBuilder.Entity("FreestyleApplication.Models.User", b =>
                {
                    b.HasOne("FreestyleApplication.Models.Competition", null)
                        .WithMany("Users")
                        .HasForeignKey("CompetitionId");
                });

            modelBuilder.Entity("FreestyleApplication.Models.Competition", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
